name: Deploy MultiK8s
on:
  push:
    branches:
      - main

env:
  SERVICE_ACCOUNT: '${{ secrets.SERVICE_ACCOUNT }}'
  SHA: $(git rev-parse HEAD)
  LOCATION: europe-west1-b
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: react-app-test

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: |-
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker build -t fracc/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true fracc/react-test npm test

      - name: Set Identity Provider
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/950268361153/locations/global/workloadIdentityPools/docker-react-test-pool/providers/docker-react-test-provider'
          service_account: '${{ env.SERVICE_ACCOUNT }}@${{ env.GKE_PROJECT }}.iam.gserviceaccount.com'

      - name: Get Credentials
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.LOCATION }}

      - name: Set Project
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ env.GKE_PROJECT }}

      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker

      - name: Build
        run: |-
          docker build -t fracc/multi-client:latest -t fracc/multi-client:${{ env.SHA }} ./client 
          docker build -t fracc/multi-server:latest -t fracc/multi-server:${{ env.SHA }} ./server 
          docker build -t fracc/multi-worker:latest -t fracc/multi-worker:${{ env.SHA }} ./worker

      - name: Push
        run: |-
          docker push fracc/multi-client:latest
          docker push fracc/multi-server:latest
          docker push fracc/multi-worker:latest
          
          docker push fracc/multi-client:${{ env.SHA }}
          docker push fracc/multi-server:${{ env.SHA }}
          docker push fracc/multi-worker:${{ env.SHA }}

      - name: Apply
        run: |-
          kubectl apply -f k8s
          kubectl set image deployments/client-deployment client=fracc/multi-client:${{ env.SHA }}
          kubectl set image deployments/server-deployment server=fracc/multi-server:${{ env.SHA }}
          kubectl set image deployments/worker-deployment worker=fracc/multi-worker:${{ env.SHA }}
